#!/bin/bash

# Still a work in progress!

#   Pseudocode:

#   Make folder in /Users/$USER/Desktop called ExtractedVidFrames
#   Make folder in /Users/$USER/Desktop/ExtractedVidFrames called Banneker
#   Make folder in /Users/$USER/Desktop/ExtractedVidFrames called JFK
#   Make folder in /Users/$USER/Desktop/ExtractedVidFrames called Unknown
#   Go to the folder NIH2018_Data/Video
#   for i from 1 to 5:
#       Enter the folder /Session + i + /
#       Make folder in /Users/$USER/Desktop/ExtractedVidFrames/Banneker called /Session + i + /
#       Make folder in /Users/$USER/Desktop/ExtractedVidFrames/JFK called /Session + i + /
#       Make folder in /Users/$USER/Desktop/ExtractedVidFrames/Unknown called /Session + i + /
#       for every file ending with the .MP4 extension
#           Split the file name by "_" and store the first string in a var called name
#           if name starts with "p0"
#               Make the dir /Users/$USER/Desktop/ExtractedVidFrames/Banneker/$name if it doesn't already exist
#               count the number of directories in /Users/$USER/Desktop/ExtractedVidFrames/Banneker/$name and store in a variable called count
#               Make a folder in /Users/$USER/Desktop/ExtractedVidFrames/Banneker/$name called (count + 1)
#               Enter the newly created folder
#           else if name starts with "p1"
#               Make the dir /Users/$USER/Desktop/ExtractedVidFrames/JFK/$name if it doesn't already exist
#               count the number of directories in /Users/$USER/Desktop/ExtractedVidFrames/JFK/$name and store in a variable called count
#               Make a folder in /Users/$USER/Desktop/ExtractedVidFrames/JFK/$name called (count + 1)
#               Enter the newly created folder
#           else
#               Make the dir /Users/$USER/Desktop/ExtractedVidFrames/Unknown/$name if it doesn't already exist
#               count the number of directories in /Users/$USER/Desktop/ExtractedVidFrames/Unknown/$name and store in a variable called count
#               Make a folder in /Users/$USER/Desktop/ExtractedVidFrames/Unknown/$name called (count + 1)
#           
#           calculate video duration using ffprobe and store it in a var called duration
#           create variables called startTime and durationTime
#           if duration is greater than 7 minutes
#               set startTime to 2min and durationTime to 5min
#           else if duration is greater than 5 minutes
#               set startTime to (duration minus 5 minutes), and set durationTime to 5 min
#           else
#               set startTime to 0
#               set durationTime to duration
#
#           use ffmpeg to generate frames, starting at startTime and lasting durationTime, cutting the height and width in half, at 3 fps, using the name "frame%05d.bmp" and stored in the current folder
#       cd to NIH2018_Data/Video

pathToAllVids="/Users/$USER/Dropbox (MIT)/NIH2018_Data/Video/"

vidlength=$(ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 "/users/$USER/Dropbox (MIT)/NIH2018_Data/Video/Session1/Compressed/p001_s1_1_edited.MP4")

echo $vidlength