#!/bin/bash

# Still a work in progress!

#   Pseudocode:

#   for every folder in /Users/$USER/Desktop/ExtractedVidFrames/: (Banneker, JFK, Unknown)
#       store the folder name in a var called schoolName
#       for i from 1 to 5:
#           Enter the folder /Session + i + /
#           for every folder in the directory: (p001, p002, ... or p100, p102, ... or empty)
#               store the folder name in a var called pName
#               get the id using the -getId TerminalUtils action and store in a var called pId
#               if pId equals null:
#                   create the person in personGroup $schoolName with the name $pName and store the returned id in pId
#               for every folder in the directory:
#                   store the folder name in a var called imgPath
#                   run the CustomTrainingArgs program with personGroupId $schoolName, personId $pId, image path $imgPath and the -no_training flag